services:
  raftkb-flask-server:
    build: ./raft-knowledge-base-website
    container_name: flask-app
    restart: unless-stopped
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 500m
        reservations:
          memory: 256m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 100m
        reservations:
          memory: 64m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ionos-updater:
    build: ./ionos-updater
    container_name: ionos-updater
    volumes:
      - ./ionos-updater/data:/data
    restart: unless-stopped
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web:
    driver: bridge